version: '3.4'
services:
  exchange-api-1:
    container_name: exchange-api-1
    image: mock_exchange:latest
    command: python rest.py
    environment:
      - EXCHANGE_ID=1
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
    depends_on:
      - redis
    links:
      - redis:redis

  exchange-ws-1:
    container_name: exchange-ws-1
    image: mock_exchange:latest
    command: python ws.py
    environment:
      - EXCHANGE_ID=1
    ports:
      - "8765:8765"
    volumes:
      - ./src:/code
    depends_on:
      - redis
    links:
      - redis:redis

  exchange-api-2:
    container_name: exchange-api-2
    image: mock_exchange:latest
    command: python rest.py
    environment:
      - EXCHANGE_ID=2
    ports:
      - "8001:8000"
    volumes:
      - ./src:/code
    depends_on:
      - redis
    links:
      - redis:redis

  exchange-ws-2:
    container_name: exchange-ws-2
    image: mock_exchange:latest
    command: python ws.py
    environment:
      - EXCHANGE_ID=2
    ports:
      - "8766:8765"
    volumes:
      - ./src:/code
    depends_on:
      - redis
    links:
      - redis:redis

  exchange-api-3:
    container_name: exchange-api-3
    image: mock_exchange:latest
    command: python rest.py
    environment:
      - EXCHANGE_ID=3
    ports:
      - "8002:8000"
    volumes:
      - ./src:/code
    depends_on:
      - redis
    links:
      - redis:redis

  exchange-ws-3:
    container_name: exchange-ws-3
    image: mock_exchange:latest
    command: python ws.py
    environment:
      - EXCHANGE_ID=3
    ports:
      - "8767:8765"
    volumes:
      - ./src:/code
    depends_on:
      - redis
    links:
      - redis:redis

  redis:
    restart: always
    container_name: redis
    image: redis:5.0-rc4
    expose:
      - "6379"
